---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  #MYSQL_REPLICATION_USER: repl
  #MYSQL_REPLICATION_PASSWORD: replpassword
