apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-primary-config
  namespace: mysql
data:
  mysql.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog-format=ROW
    gtid-mode=ON
    enforce-gtid-consistency=ON
    bind-address=0.0.0.0
